# Generated by Django 6.0.3 on 2026-04-23 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0002_motherboard_psu_storage'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpu',
            name='socket',
            field=models.CharField(default='AM4', help_text='Наприклад: AM4, LGA1700', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='motherboard',
            name='ram_type',
            field=models.CharField(default='DDR4', max_length=10),
        ),
        migrations.AddField(
            model_name='ram',
            name='ram_type',
            field=models.CharField(default='DDR4', help_text='DDR4 або DDR5', max_length=10),
        ),
    ]
