# Generated by Django 6.0.3 on 2026-04-23 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0003_cpu_socket_motherboard_ram_type_ram_ram_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Build',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cpu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='configurator.cpu')),
                ('gpu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='configurator.gpu')),
                ('motherboard', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='configurator.motherboard')),
                ('psu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='configurator.psu')),
                ('ram', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='configurator.ram')),
                ('storage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='configurator.storage')),
            ],
        ),
    ]
